/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REQUIRE = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int FOR = 8;
  /** RegularExpression Id. */
  int FUNC = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DEF = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int NAME = 15;
  /** RegularExpression Id. */
  int ASSIGNMENT = 16;
  /** RegularExpression Id. */
  int RETURNSYMBOL = 17;
  /** RegularExpression Id. */
  int ADD = 18;
  /** RegularExpression Id. */
  int SUB = 19;
  /** RegularExpression Id. */
  int MUL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int EQ = 22;
  /** RegularExpression Id. */
  int NEQ = 23;
  /** RegularExpression Id. */
  int LESS = 24;
  /** RegularExpression Id. */
  int GREATER = 25;
  /** RegularExpression Id. */
  int LESSOREQUAL = 26;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 27;
  /** RegularExpression Id. */
  int OBRACKET = 28;
  /** RegularExpression Id. */
  int CBRACKET = 29;
  /** RegularExpression Id. */
  int OBRACE = 30;
  /** RegularExpression Id. */
  int CBRACE = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"require\"",
    "\"if\"",
    "\"while\"",
    "\"for\"",
    "\"func\"",
    "<STRING>",
    "<DIGIT>",
    "<INTEGER>",
    "\"def\"",
    "<LETTER>",
    "<NAME>",
    "\"=\"",
    "\"->\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\" >\"",
    "\"<=\"",
    "\" >=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
